import {initializeApp} from 'firebase/app';
import {getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut} from 'firebase/auth';
import './styles.css';

const firebaseConfig={apiKey:'AIzaSyC9_g7DblKRamrFdM2xBKK03Q-MUJM6tt4',authDomain:'wycoder.firebaseapp.com',projectId:'wycoder',storageBucket:'wycoder.firebasestorage.app',messagingSenderId:'610749661041',appId:'1:610749661041:web:37daf5af5946838914c0d0'};
const app=initializeApp(firebaseConfig),auth=getAuth(app);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(action,body={}){const u=auth.currentUser;if(!u)throw new Error('Sign in as an admin first.');const token=await u.getIdToken();const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({action,...body})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Admin request failed.');return j}
const state={page:'sellers-lab',data:null,msg:'',loading:false,search:[],searchQ:''};
const pages=[['sellers-lab','Sellers Lab'],['appeals','Appeals'],['reports','Reports'],['sellers','Sellers']];
function renderLogin(){document.querySelector('#app').innerHTML=`<main class="auth"><div class="box"><span class="eyebrow">W Y C O D E</span><h1>Admin</h1><p>Restricted marketplace administration.</p><form id="login"><input id="email" type="email" autocomplete="username" placeholder="Admin email" required><input id="password" type="password" autocomplete="current-password" placeholder="Password" required><button>Sign in</button><p id="msg" class="msg"></p></form></div></main>`;document.querySelector('#login').onsubmit=async e=>{e.preventDefault();const m=document.querySelector('#msg');try{await signInWithEmailAndPassword(auth,document.querySelector('#email').value.trim(),document.querySelector('#password').value);m.textContent='Checking admin access…';await load()}catch(err){m.textContent=err.message.replace(/^Firebase:\s*/,'')}}}
async function load(){state.loading=true;render();try{state.data=await api('overview');state.msg=''}catch(e){state.msg=e.message}finally{state.loading=false;render()}}
function card(p){const a=p.codeAudit||p.audit||{};return `<article class="card"><div class="row"><div><span class="tag">${esc(p.category)}</span><h3>${esc(p.name)}</h3><p>${esc(p.sellerName||'Developer')}</p></div><span class="sales">${Number(p.sales||0)} sales</span></div><div class="meta"><span>★ ${Number(p.ratingAverage||0).toFixed(1)} · ${Number(p.ratingCount||0)} reviews</span><span>Rank ${Number(p.rankScore||0).toFixed(1)}</span></div><div class="audit ${a.status||'pending'}"><b>Code audit: ${esc(a.status||'pending')}</b><small>${esc(a.summary||'Audit not completed yet.')}</small>${Array.isArray(a.errors)&&a.errors.length?`<details><summary>${a.errors.length} issue(s)</summary>${a.errors.slice(0,10).map(e=>`<p>${esc(e.file)}:${Number(e.line||0)}:${Number(e.column||0)} — ${esc(e.message)}</p>`).join('')}</details>`:''}</div><div class="actions"><button class="action" data-special="${esc(p.id)}">${p.special?'Remove special':'Label as special sales'}</button><button class="suggestBtn" data-suggest="${esc(p.id)}">${p.suggested?'UNSUGGEST':'SUGGEST'}</button><button data-audit="${esc(p.id)}">Re-run audit</button>${a.status==='attention'?`<button class="danger" data-alert="${esc(p.id)}">Alert seller</button>`:''}</div></article>`}
function appealCard(a){return `<article class="card"><div class="row"><div><span class="tag">${esc(a.status||'pending')}</span><h3>${esc(a.accountName||a.sellerName||a.uid)}</h3><p>${esc(a.category||'Unspecified')}</p></div><small>${esc(a.createdAt||'')}</small></div><p>${esc(a.description||a.appealDescription||'')}</p>${a.status==='pending'?`<div class="actions"><button data-decision="approve" data-id="${esc(a.id)}">Approve</button><button class="danger" data-decision="reject" data-id="${esc(a.id)}">Reject</button></div>`:''}</article>`}
function render(){const root=document.querySelector('#app');if(!auth.currentUser){renderLogin();return}if(!state.data){root.innerHTML='<main class="auth"><div class="box"><p>Loading admin data…</p></div></main>';return}root.innerHTML=`<header><div><b>WyCode Admin</b><small>Marketplace control center</small></div><button id="menu">☰</button></header><div class="layout"><nav id="nav" class="${state.page?'':'open'}">${pages.map(([id,label])=>`<button class="${state.page===id?'active':''}" data-page="${id}">${label}</button>`).join('')}<button id="logout">Sign out</button></nav><main class="content"><div class="top"><div><span class="eyebrow">${esc(pages.find(x=>x[0]===state.page)?.[1]||'ADMIN')}</span><h1>${state.page==='sellers-lab'?'Sellers Lab':state.page[0].toUpperCase()+state.page.slice(1)}</h1></div><div class="adminSearch"><input id="smartSearch" placeholder="Smart search descriptions, categories, sellers…" value="${esc(state.searchQ)}"><button id="searchBtn">Search</button></div><button id="refresh">Refresh</button></div>${state.msg?`<div class="notice">${esc(state.msg)}</div>`:''}${state.loading?'<p>Loading…</p>':''}${pageBody()}</main></div>`;
root.querySelector('#menu').onclick=()=>root.querySelector('#nav').classList.toggle('open');root.querySelector('#logout').onclick=()=>signOut(auth);root.querySelector('#refresh').onclick=load;root.querySelector('#searchBtn').onclick=async()=>{const q=root.querySelector('#smartSearch').value.trim();state.searchQ=q;if(!q){state.search=[];render();return;}try{const r=await api('smart-search',{q});state.search=r.products||[];state.msg='';render()}catch(e){state.msg=e.message;render()}};root.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;root.querySelector('#nav').classList.remove('open');render()});root.querySelectorAll('[data-special]').forEach(b=>b.onclick=async()=>{try{await api('toggle-special',{productId:b.dataset.special});await load()}catch(e){state.msg=e.message;render()}});root.querySelectorAll('[data-suggest]').forEach(b=>b.onclick=async()=>{try{const r=await api('toggle-suggest',{productId:b.dataset.suggest});state.msg=r.ok?(r.suggested?'Product approved for Suggested.':'Product removed from Suggested.'):(r.message||'Product did not pass the audit.');await load()}catch(e){state.msg=e.message;render()}});root.querySelectorAll('[data-decision]').forEach(b=>b.onclick=async()=>{const description=prompt(`Optional note for ${b.dataset.decision}:`)||'';try{await api('decide-appeal',{appealId:b.dataset.id,decision:b.dataset.decision,note:description});await load()}catch(e){state.msg=e.message;render()}});root.querySelectorAll('[data-audit]').forEach(b=>b.onclick=async()=>{try{await api('audit-product',{productId:b.dataset.audit});await load()}catch(e){state.msg=e.message;render()}});root.querySelectorAll('[data-alert]').forEach(b=>b.onclick=async()=>{try{await api('alert-seller',{productId:b.dataset.alert});state.msg='Seller notification sent.';render()}catch(e){state.msg=e.message;render()}})}
function pageBody(){if(state.searchQ)return `<div class="sectionHead"><h2>Smart search results</h2><span>${state.search.length} matches</span></div><div class="grid">${state.search.map(card).join('')||'<div class="empty">No matching products.</div>'}</div>`;if(state.page==='sellers-lab')return `<div class="grid">${(state.data.products||[]).map(card).join('')||'<div class="empty">No listed products.</div>'}</div>`;if(state.page==='appeals')return `<div class="grid">${(state.data.appeals||[]).map(appealCard).join('')||'<div class="empty">No appeals.</div>'}</div>`;if(state.page==='reports')return `<div class="stats"><div><b>${Number(state.data.reportCount||0)}</b><span>Total reports</span></div><div><b>${Number(state.data.bannedCount||0)}</b><span>Banned sellers</span></div></div><div class="grid">${(state.data.reports||[]).map(r=>`<article class="card"><span class="tag">${esc(r.reason)}</span><h3>${esc(r.sellerName||r.sellerUid)}</h3><p>${esc(r.createdAt||'')}</p></article>`).join('')||'<div class="empty">No reports.</div>'}</div>`;return `<div class="grid">${(state.data.sellers||[]).map(s=>`<article class="card"><span class="tag">${s.banned?'BANNED':esc(s.tier||'free')}</span><h3>${esc(s.displayName||'Developer')}</h3><p>${esc(s.email||'')}</p><div class="meta"><span>${Number(s.reportCount||0)} reports</span><span>$${Number(s.balanceUSD||0).toFixed(2)} balance</span></div></article>`).join('')||'<div class="empty">No sellers.</div>'}</div>`}
onAuthStateChanged(auth,u=>{if(u)load();else renderLogin()});
